name: NMCRewards
version: '1.0'
main: me.bubbles.nmcrewards.NMCRewards
commands:
  namemc:
    usage: /<command>
    description: Claim rewards for liking the server on NameMC
    aliases: [nmc, claimnmc, nmcclaim, namemcclaim]